### ISSUE TITLE
where is the L

### ISSUE THREAD

**Issue by Jiadosi** [SoftSec-KAIST/IMF#1]
Hi!
I am studying your IMF but I cannot find the input of L(the number of logs to take).
Can you tell me where I can set this value?
Thanks a lot!

**Comment by DaramG** [comment]
Put the `L` log files in the `log dir` when you execute `filter-log` like bellow.
```
$ ./filter-log [log dir] [output dir] [# of output(filtered log)] [# of core]
```

**Comment by Jiadosi** [comment]
Thanks for the reply!
You mean I have to generate log files one by one at the second step?
Because I found only one log file generated when execute the line below.
`$ DYLD_INSERT_LIBRARIES=[hooking library path] [program path] [program args]`

**Comment by DaramG** [comment]
Yes, you should generate log files one by one.
I recommend you to write some script for that.

**Comment by Jiadosi** [comment]
I see. Thanks a lot!!!
Appreciate your work!
