### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by ghost** [SoftSec-KAIST/IMF#4]
you got any idea how to avoid segfaulting on arch64?
im' clueless here,
what arch did you run this at?
with what clang version?

the generated fuzzers segfaults for me...
in all sorts of different places

best

**Comment by ghost** [comment]
nevermind this is the answer: https://stackoverflow.com/questions/53610512/i386-architecture-deprecated-in-macos-error

**Comment by akayn** [comment]
ho wel.. thats not the answer...
i guess this is too old and dysfunctional..
